const CONFIG = {
    ROWS_TABLE_QTY: 4,
    COLUMNS_TABLE_QTY: 4,
    DROP_PERCENT_4_AT_FIRST: 0.1,
    STARTED_VALUE: 2,
    GAME_TABLE_CLASSES: ['game-table', 'section-game__game-table'],
    GAME_TABLE_BODY_CLASSES: ['game-table__body', 'section-game__game-table-body'],
    GAME_TABLE_ROW_CLASSES: ['game-table__row'],
    GAME_TABLE_CELL_CLASSES: ['game-table__cell', 'section-game__game-table-cell'],
    GAME_IS_ACTIVE: true,
    ARROW_UP: 'ArrowUp',
    ARROW_DOWN: 'ArrowDown',
    ARROW_LEFT: 'ArrowLeft',
    ARROW_RIGHT: 'ArrowRight',
    ASCENDING_SORT: 'ASCENDING_SORT',
    DESCENDING_SORT: 'DESCENDING_SORT',
    MODAL_ACTIVE_CLASS: 'modal_active',
    OVERLAY_CLASS: 'overlay',
    VISIBILITY_HIDDEN_CLASS: 'visibility-hidden',
    TABLE_BUTTON: document.querySelector('[data-accessory="table"]'),
    MODAL: document.querySelector('.modal'),
    STORAGE_KEY_RECORD_DEGREE: 'record-degree',
    RECORD_DEGREE: document.querySelector('[data-record]'),
    STORAGE_KEY_CELLS_VALUES: 'cells-values',
};

export default CONFIG;
